hello: ENC[AES256_GCM,data:i0PwHRp4L7KRPO+wbNmDyGEcnZ2eMnvC+ZAB,iv:y6mqZ6JHggSDHkJfKGC2wZ++7NLQt1rGsviC1CfOINs=,tag:SYiTHkWhEpESkhdmRIJ6zQ==,type:str]
example_key: ENC[AES256_GCM,data:2KGdwgtMQ4RHk4rNSg==,iv:Citqj+1cYhFuGc2BoKPzPX4TF80FHELbvEMjov5Tlkk=,tag:PitMcDa81Xe3dsra8lbQRA==,type:str]
#ENC[AES256_GCM,data:ZIy+hX6mBiYsx22JkKy6Wg==,iv:YwLjQbETsQXmdq27ZPvOti1djDYYrCV8AkdghWlgWiw=,tag:c5Q72rLj0ZsN25LhEjVQRw==,type:comment]
example_array:
    - ENC[AES256_GCM,data:BfCa/cdRWPnbYlkKMtA=,iv:UrNDm3qIzzdNUB2rHGcLJMJHp2PvVOsnEfJM3H8VlDY=,tag:6FYDrT8K2JjxLPXtVoe61w==,type:str]
    - ENC[AES256_GCM,data:s4jmo01/gNM9b0CRSm4=,iv:FG/n/WEZokq3WmMoneGVub5dPH9v1aupph8E+Sny8+g=,tag:KQuJwx6YTLprGLqgRTBRtA==,type:str]
example_number: ENC[AES256_GCM,data:6koiT1/iq0Fxww==,iv:qGgfTKLFX2C6MUwE7s0TvAVChBCNzjbWC3bTbtNLlts=,tag:kyBre16ZTNdBwinCd5a16Q==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:ZUAsMA==,iv:+RUVdXpoYr8rb5VE5hI8CEboyVnld4G7/EAV0hEX/gw=,tag:v0FvVYbnVvVw9lolvvhcTA==,type:bool]
    - ENC[AES256_GCM,data:rwTLTBg=,iv:HRVD9F8Uh2CbeNiqf6WzePOegXeG4oCm2Ij99rB69Oc=,tag:9OhfH2nJxpA4aRCoOOsSTA==,type:bool]
sops:
    age:
        - recipient: age1r9g435pu74yvnp8t44jj7z4qfj829v3w43ae7fgzxvusqu3y9cnq9pute3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRXpxd1R6cUxXR2NNU1lW
            Y1o4MGhpZXJJSnNTQXlMRU1MdzBNc2luNWpvCkt1ZzJOVUE1WWMyaTFtMWk2bkZS
            VnAxMDc3aWFjK3dpL0VBaXRYU1lDaTQKLS0tIExkWjJRNGIvMjBpMWN1TkVqQjhy
            VHpqWHdZZFN4cDdCKzdGcnBnK1IrT0EKeDGFTuFndnhXjrwqvMPMpmwBKTFyKw89
            qvK4Tqf/n3vnRQZ2qBM8saiWNiqZN869KERdyswAt68WA3A2c7G0pQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zlmedva0jsdys79d39qgy595clx5zemjzl2w0qpgewq2psj5yggswgltf2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxL1F5TkdPNFZSR0JkRUxz
            eTB6VHlHeUtEVUZuVVp2cXQ2a3kySmVoN3l3ClhOLzdXVHZZZmprZTJrYWJhYVpK
            R3JPR09XbWpNZkxXUDdab2RyQmpnQzQKLS0tIHNuTGdNb2w2OXVkbk9lZEwweStZ
            OGFrU1RLSEpWYjVJWWxEZVB4YzF1V2MKhz0ijTF7Ilzw4LsSDzROBVBKVR2kj6VJ
            P9meyH7cHT92MjZrQMfZwoYJUZH/E/Al3RA/J+JGiNnt0IooEZP3wg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10fg3nznhct8ke3h2yckdxp2vm3hhh5ej9s3w4adzm8p55twamsrqhnaq3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRmxLTGdxaU81VE4vckFO
            dzZuUnh5T1FXbnAyWktmQmhYeGFmbWtQZERZCnJNWkNWNExtTXRaemlvMHpwcExt
            WC9KL29OYTFkNkxBRzJrTFgvZFFFdTgKLS0tIG5hMGN4VTdhdEZUd2ZzVDBySytX
            UFozaktkbFk2RmRxMzR1S2FNMEZBNlkKs6O5vm32x1iuQ8QOLQOuUzIPMiO6p8jS
            EluvQMZ0RtY5WSWzXMu+h2SY/sbHSqMPf9RkUFmLjCeymPbVs1vg5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T21:05:33Z"
    mac: ENC[AES256_GCM,data:2qWUZ9uJKu31Bb6dl7TngN6ZnBHiPWvSdPEeoHO1zwdgu6uQxiy3MnUoEpBZAyjLBgDeRkKAmpuDdMHJTjecOOD8ywgvcu22drXsieEPD8HVyk2aa6mTDjRMeW9B2gdUHV7NmiHy1wp3HmaVVgpiT+oa+ZYfXYFl+MpkifnUZcs=,iv:g2AsYQY1RYPpHWx0FCaav2d6LKWhq/5HmEb7duh2XDE=,tag:KALcbQU89nAtHIZ8OO0WiA==,type:str]
    pgp:
        - created_at: "2026-06-12T21:22:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4SYQepcDT7yARAAuJBoz95d64PO5gXFiFn1YBqq/9h5EvGzHTTW66N7D77D
            PJAopnlHTMhJHx0JLm4xSO42FqMMWdT4GVbGczqu1s3b4KfvnBO6ZO0lFSHdF/rt
            4/Bqa4QC3Y1W2HRn9DndEu0xdmDQVYMIoujSX0RUUyQ8vrJwGmIm0lorKtYYi8+d
            RwFefXgrvimT+BKiO6rL9EIEdMh7CEMJe3/5uyg6ey+9VagQ+YyAfdAIOT7N03ZH
            WnGC5g4C2uVcgOfDFI8PyAbhs1WBmR91GxCvh5KVSoB+0S++t4SNdqnCeAdx7ADO
            T+nChqwT9/A7Jf3TT/qhpswj74iIvVl+mBbGrclSlOs4bMtUjcUwcST8CmVnUCbh
            CTHnUM0etkQlL59j5P+FHBF1lmcBYEFUTGhgbcx2Qcj4HH4/6zOudXTz5wqX8yxU
            YUpHpaci/YVNHXINZy0MnPY3vcIIqVRpLCMgL0o7pLpwOjvjUnB7JZBSxdJ7Sknk
            +N2VW1G+nVfPl9Mhvl0QEbO7FqCbZW5bwz9YOw6qfbJ1iMTWN6aq+rU5KeX378a9
            BLtKBsp/fpEr0WKqCDZ4ExdBzLHnj8ntGdcvkD0oFHAmQGD9ENmy2xbXa98akuhF
            +SXr7LmlEtegh1TapmRMoZVScCbFh1N/KE0GPQ12G5rBQBU77uUvcgVJUZJ2AIHS
            WAGtCJMj6noMJAeT6Q3nHa+dtX7G9dF08Q3AnSG7CI/RsmCUYethNAUfZp7qqYJc
            52j506QnB4dJ4Sy05PtIxKIAfRBHpbafdh8Q6/vnDotMPT8NPdCmUzU=
            =omH6
            -----END PGP MESSAGE-----
          fp: B054287D42FC91AD36137D9F03ECA132FD38CD59
    unencrypted_suffix: _unencrypted
    version: 3.13.1
