hello: ENC[AES256_GCM,data:i0PwHRp4L7KRPO+wbNmDyGEcnZ2eMnvC+ZAB,iv:y6mqZ6JHggSDHkJfKGC2wZ++7NLQt1rGsviC1CfOINs=,tag:SYiTHkWhEpESkhdmRIJ6zQ==,type:str]
example_key: ENC[AES256_GCM,data:2KGdwgtMQ4RHk4rNSg==,iv:Citqj+1cYhFuGc2BoKPzPX4TF80FHELbvEMjov5Tlkk=,tag:PitMcDa81Xe3dsra8lbQRA==,type:str]
#ENC[AES256_GCM,data:ZIy+hX6mBiYsx22JkKy6Wg==,iv:YwLjQbETsQXmdq27ZPvOti1djDYYrCV8AkdghWlgWiw=,tag:c5Q72rLj0ZsN25LhEjVQRw==,type:comment]
example_array:
    - ENC[AES256_GCM,data:BfCa/cdRWPnbYlkKMtA=,iv:UrNDm3qIzzdNUB2rHGcLJMJHp2PvVOsnEfJM3H8VlDY=,tag:6FYDrT8K2JjxLPXtVoe61w==,type:str]
    - ENC[AES256_GCM,data:s4jmo01/gNM9b0CRSm4=,iv:FG/n/WEZokq3WmMoneGVub5dPH9v1aupph8E+Sny8+g=,tag:KQuJwx6YTLprGLqgRTBRtA==,type:str]
example_number: ENC[AES256_GCM,data:6koiT1/iq0Fxww==,iv:qGgfTKLFX2C6MUwE7s0TvAVChBCNzjbWC3bTbtNLlts=,tag:kyBre16ZTNdBwinCd5a16Q==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:ZUAsMA==,iv:+RUVdXpoYr8rb5VE5hI8CEboyVnld4G7/EAV0hEX/gw=,tag:v0FvVYbnVvVw9lolvvhcTA==,type:bool]
    - ENC[AES256_GCM,data:rwTLTBg=,iv:HRVD9F8Uh2CbeNiqf6WzePOegXeG4oCm2Ij99rB69Oc=,tag:9OhfH2nJxpA4aRCoOOsSTA==,type:bool]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeUp5VGEwMGVyMVhMWmdr
            L09kY0hpMVE4aTZIUC9RY0VjQ1FVN0lOVWl3CnQ1c3diZnBlYThoUnNjZTRVZERy
            ZlZ2SHMxaGNmb00zTHA5eWVxdkJINDQKLS0tIGJaYlFkck1RdVZPdHh6S0lIYTNH
            ZXJ3VS9WcS91bDY2WEhxK3NBUm1la3cKELB3alxHxAhh8mVMyXuiGDVS6aWYn4rX
            Pcq016ejbCUr+V9dBUp9sMUGZjI5GzdX8g7bNn4Ed/HvnXvVSTJrhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r9g435pu74yvnp8t44jj7z4qfj829v3w43ae7fgzxvusqu3y9cnq9pute3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRR1JVOUc5NFZPdEYvTkh6
            VW94RkU5VzhBa3RKZ0VVNHJDYWxvbjkxaHdBCngwKzBBbktGSWQ0QlhaWFZ3VWNW
            R01BM0xpWWNJZ3VKZXFONnJTYmpGWGcKLS0tIGFtRVVSaFpEM0hjYy95bk11VlNJ
            NzZCUm1mQTJER042MzdaNURnTlp0eEkK5oQRZUbsG5dkfg1cRiioDCMXLBc3W/UK
            FrEyqlfjhuXhscB0phh25Bd3TgQSOxOY224XI0y1xBlzgtl6pA8fxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zlmedva0jsdys79d39qgy595clx5zemjzl2w0qpgewq2psj5yggswgltf2
    lastmodified: "2026-06-12T21:05:33Z"
    mac: ENC[AES256_GCM,data:2qWUZ9uJKu31Bb6dl7TngN6ZnBHiPWvSdPEeoHO1zwdgu6uQxiy3MnUoEpBZAyjLBgDeRkKAmpuDdMHJTjecOOD8ywgvcu22drXsieEPD8HVyk2aa6mTDjRMeW9B2gdUHV7NmiHy1wp3HmaVVgpiT+oa+ZYfXYFl+MpkifnUZcs=,iv:g2AsYQY1RYPpHWx0FCaav2d6LKWhq/5HmEb7duh2XDE=,tag:KALcbQU89nAtHIZ8OO0WiA==,type:str]
    pgp:
        - created_at: "2026-06-12T21:05:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4SYQepcDT7yAQ//e3/2FaTXzeeEw5Do39H7k9KZlz8XKPJO9smLisDSyt6X
            Lrb51FT/SX51yFrnhRrXRNdgFd9pLCgemrd4mHcDyU8Z7Vh633Nta5VkyfxUe+kJ
            kXCfgSBYRp7GLEWmzUp68mdR1Gij0JTA67Zb6LNL1KdDTAP/3oFlZDI4CO3Ws31H
            DZtio0ThYI8vDfQUizs0rmGc2J0Ug7+qnEM1G3HDvJYmFrnbBti37PlInQGYiemH
            JWKWqmVNeMj2kxWTcDaxULW1iaP9y5GDYpHKnPXIPS5LyXNkMNdBGjRbhuTr1CbQ
            Iv4IbR8vmYHs8mzvJ3XdNyJvX4+5cfGzzqyxn74RQiuKZferL0Mqy4lb0/cJ3ZA2
            u3harAcMzPmQJ49Z/ExIxXyIIQmOWUcxWGK2+ONeuBW3vjqWH106x3fsb9GbZENb
            k4wthCVLTytpeTMOoG/3vVik8xrrLXlSL611e4A5l8wPEfaaAcfhVY4ZijpIw1Um
            DnxAu7XLmIgevJVcYbc0EL1Iy35iUtiER134QklhYIxjmDW2MBU8Avo5JGaL3lmH
            Vs1oex9zUyA9O5e4pWr5nIsM6JxFoXoEn9nFCjvTMuXqgmFI1sB5W9kB+rJ4XZju
            roPVSZjOjX51z9sqEe4XvzWIojEKb81WY0q3UPJ4F18usMmNUbBOYVa/odubR8HS
            WAHApDeUEB/OuGkNUfO9+sYAz1XuDa6GN2DgIFYsmLiS4YLYO30Yfb2PJcH2TAYP
            xyuQ0yUk0Ay54n7azg69x8IPK2bAd4JAbePiW+EQlNMaoHF2K81xxGs=
            =cNt7
            -----END PGP MESSAGE-----
          fp: B054287D42FC91AD36137D9F03ECA132FD38CD59
    unencrypted_suffix: _unencrypted
    version: 3.13.1
