keys:
  - &admin B054287D42FC91AD36137D9F03ECA132FD38CD59
  - &t420 age1zlmedva0jsdys79d39qgy595clx5zemjzl2w0qpgewq2psj5yggswgltf2
  - &vps2-de-berlin age1r9g435pu74yvnp8t44jj7z4qfj829v3w43ae7fgzxvusqu3y9cnq9pute3
creation_rules:
  - path_regex: ^secrets/vps2-de-berlin/.*$
    key_groups:
      - pgp:
          - *admin
        age:
          - *t420
          - *vps2-de-berlin 
  - path_regex: ^secrets/t420/.*$
    key_groups:
      - pgp:
          - *admin
        age:
          - *t420
          - *vps2-de-berlin
  - path_regex: ^secrets/
    key_groups:
      - pgp:
          - *admin
        age:
          - *vps2-de-berlin
          - *t420
