hello: ENC[AES256_GCM,data:Q6zvLp2yyuVDjVTIaAWGUBPmW6yo5bmcmnKibiQX2Y3brAb/ZteMAGyNK0UZZw==,iv:rCHVPEuZsd25H0wI/xUBmcHR8GZDud4LXLys60ZeEyE=,tag:tZB49KOM83VRmPs5JCUSZA==,type:str]
sops:
    age:
        - recipient: age1zlmedva0jsdys79d39qgy595clx5zemjzl2w0qpgewq2psj5yggswgltf2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aVFLSlIvYmE1OFNFaGpW
            aEJtUHVxeEhGQUhUTXNSYTd2cmhqM0x3Qm5FCm16Z0xtblJkSURGTlN1RUlSanFR
            eWpMc3lVdEMvV3BuSzNpczcxdUhkYmsKLS0tIERYeHB2RDNuTzFHN3lGSlVBMHdu
            eitEV1lqbFM5QjBOZjhjak5jTlRXSk0Ka8M2Tr9o1f9fbdkScH67nmqr5Bd29zPY
            ae57H2HaajVHGlmwjJNHBwQrPbZP5DuA3XZdDH6xrBsvlomEMX9W5w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r9g435pu74yvnp8t44jj7z4qfj829v3w43ae7fgzxvusqu3y9cnq9pute3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZHlyN1FvR2x1T2c0N3Mw
            d0h0TWppSDdHcERZZGVPQUl3TWxwSU5CMXdnCk9wbXRmMFVJcmRYN3dSalBvY2k5
            VFhzcmkzVnovTUsxZS9LekkwVFhkbk0KLS0tIG11U1FXNkk0N0R1MkhPU1lDM0JY
            U2xCLy80TFQ4Y2FlVmxLVGpRTnJGa00K/rcoPgobv4B1azHogHgSGiXBrkM4Q07b
            bJKZ+sHMWuQZ0DWRJxNgCPEEZehCYxnv7p9itNVE1R5KNyJzMpS69w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T15:39:09Z"
    mac: ENC[AES256_GCM,data:bVCsfG+M1R8thsjGRgQlUhodwbC0/Vb10P6HqanCAbzKb/vJ0KV4kUU/VbjTUVh9Agn003V9aIGG0WV04oKVXUEWyeil1aHwoysyEs4dAAD+oi0kOOFkrJrOMioKsJTuy7Lb/cIazzE1Jc+Tv88XOMYcqWX9AwbmA2axQkV3MVc=,iv:2O2FbjfTsu23fTMtzh4MiFs+ZQjtLCDGLCr9revVaWI=,tag:TgPD5RLsHRDsWn38iCuUjg==,type:str]
    pgp:
        - created_at: "2026-04-08T17:00:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4SYQepcDT7yARAAr8PmiOWp0cXg6hmNNN9N3tHaR3G+OWLy+nbpYP3g5gFz
            OG87EFoDvWzg8RXGDakD7WVIum9fnhDfvsm7ukr+wxM+VdO8ESzdgbbGIZTBROzd
            Ffd092vZQi70gNQQzlcKdtoL/5KbzjzRBoXZl65wCs011LagC+6IMq3x6sjFU7rq
            t1/u7RzXJQ0v6lFlgFKoT6UA8QorV3AMgDeyCnjZP5ABYaJf/9Ih52vx3QrIvY7F
            HBkqSBYuDVq2aMT6PXw0pT6QOSk5W63P9BbvcDW8D2OY9KqcPDdJhh6K8jp5YaSa
            t+buUxwZSs7e3MCR+n4aP4WGwDtkva3R0Mccd7YJow7pqJwbZboXAjKz7O5PWst4
            1xIWgJ4aPbsp6ykpLCNH19FKEZQm1v7bMrFEFai4e8LjuEPRG89rL+yhKtOiBq8l
            7mCf8hUzjVgD2NmBwht9AwOyJm3g504MF+kT4EJwXXt4+L6VuyLQSVcx6qdv7IIi
            fugklAFsdGivzmgTKy1aYguXY2kDspVSvTePRCtDenRWVRJUFfq0XZhgFV3b3qUe
            OIbbd0rfunfbWKwxAk2lWXzIC3XY2KRjTW3/2OC8QjSMyXXgqFBAbTxbEcUwKUaF
            nD4DLB/0AZ7uYQBIsAtqHU7ucBf1kxthJokq6kK2vPfDVDKpXoAo9IGCsds2aHLS
            VgEPNyhGrAQwoazcZPdTEsp7t++253LG8ea1qYc2UqvA7u49iEpQdsUm24ogUWVu
            d0RFFBG2WiPT1+i64oiR70dt5m1xCW7mlinccElOaZuGhKdYjgck
            =ICwK
            -----END PGP MESSAGE-----
          fp: B054287D42FC91AD36137D9F03ECA132FD38CD59
    unencrypted_suffix: _unencrypted
    version: 3.12.1
