hello: ENC[AES256_GCM,data:Q6zvLp2yyuVDjVTIaAWGUBPmW6yo5bmcmnKibiQX2Y3brAb/ZteMAGyNK0UZZw==,iv:rCHVPEuZsd25H0wI/xUBmcHR8GZDud4LXLys60ZeEyE=,tag:tZB49KOM83VRmPs5JCUSZA==,type:str]
sops:
    age:
        - recipient: age1zlmedva0jsdys79d39qgy595clx5zemjzl2w0qpgewq2psj5yggswgltf2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWFpoU0ZURFE1S1hRY3Zo
            ejZlQUFtdlJremZOS1VKMFVPNzU4N1hMK25VClR5NnRiNnBrQ2h6M045OUJLSHBN
            SGlYejdUdDJYMDdQWklYUDhIa1g5NTQKLS0tIG1LbnA1ZVdRWUU4S1luaURmWHl3
            bEZJR1NjdGZxbVlPdlNzMEVQWmhGbEkKG0oC63mdlclPzeNkX/rcrKyHejXH2wDk
            FvOkKI6Cm/JvoW14Fvd8S4VfKFGahbZBU4ZFIbB5ezULWtZ7t5pifA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T15:39:09Z"
    mac: ENC[AES256_GCM,data:bVCsfG+M1R8thsjGRgQlUhodwbC0/Vb10P6HqanCAbzKb/vJ0KV4kUU/VbjTUVh9Agn003V9aIGG0WV04oKVXUEWyeil1aHwoysyEs4dAAD+oi0kOOFkrJrOMioKsJTuy7Lb/cIazzE1Jc+Tv88XOMYcqWX9AwbmA2axQkV3MVc=,iv:2O2FbjfTsu23fTMtzh4MiFs+ZQjtLCDGLCr9revVaWI=,tag:TgPD5RLsHRDsWn38iCuUjg==,type:str]
    pgp:
        - created_at: "2026-04-08T15:58:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4SYQepcDT7yAQ//YvSmS8TUqXhk7mZCusuFSYz1dFiPO3d1GI1QDY8X0SOx
            L7otbApLDX90Vthn4tu7kf1Ju2ThXT8Q1PLCpfDWJb8nSh3/tsJeiEuQkCdT0Hdc
            E8KM5BzozAyuP4Ll/a/7HGrl9xKjr7Q3Rt52YiZc0nFCHjuNwe7ce0HEO0mOuLpn
            l2361YKTK8sZxPRJJatn3eoWmFAyPeKfpM4YjPWixmp7cATQemyfe/UW1Cp70VNs
            LpP6yN7vELKrhOwcrOO9Q07mHkSEpubaNw6k5s9KaJgHdRLot/zSNka3amnRaCfH
            xsI2vPXKuwiI4iSUkDkb6lu0s8t+BTjFofqX+q+iYeMim+Mj+WTWJFpX5cBo4pSg
            cX31j4+9pDNiH7xzYR/jHPfNKHA0JB67vBJDcaJa2Q9YXi2lLe4OanKhEVckFUzO
            NBrXFQrdACCC1fGU5Os0AcIAckmqzn0IZHU3CPHOANSoRFVN8fYDYWLsbvk3Dm/4
            dcxbQgTBK7zxLaVfyJ5hfG4gh/RVwob+3/wxgZDHq/Y8dJVX3ILyeW0M2CmkP8VF
            A84cWaEnVhCok7DbIpJx9MMdsgGKWcayqunOV5iHItDjansHTNRw6unIcu0pfmQB
            yyMhSBUU4zHioAAnybI55SCSeyLhqbV6GbKTkEMQ5MXjTth/OATTThb6lSrPOPTS
            VgGFVpCuY9DIPpV7CcI3JJLB5puqKU+BxlewC9Qi3wTyqbiXGLWYdmYGGxV4q3pa
            MrNXG8PchMub1H+rEw+SQI7fPvmTxZ9+6Eic9XHJzA6+vbR9yys+
            =yFlY
            -----END PGP MESSAGE-----
          fp: B054287D42FC91AD36137D9F03ECA132FD38CD59
    unencrypted_suffix: _unencrypted
    version: 3.12.1
