hello: ENC[AES256_GCM,data:BgjWrX1OTEsopVx3Umibim+aCG2WxqBcS1hSOg==,iv:Vj4+RbsImNz9YWdLebnWzuKJRditHWvsrt1jk1mdDHM=,tag:hdpYOBO4eNUFYMzkJPQzsQ==,type:str]
example_key: ENC[AES256_GCM,data:SE8N6CvdwRdKEwQQYA==,iv:EbDrKoCVxj87ONO6r0P5ap3D30pXFJHikcHnS/7DbTw=,tag:7P8LUtsRjURF99p1iz6IEw==,type:str]
#ENC[AES256_GCM,data:tLJyi9zAX/Ij+IURNHED2g==,iv:GlQUzmajAe7p3YvCrieOKeukPvQ26YKQAH/rh/5Bq1c=,tag:r2ZAxS8kjYSrDm5iRsB2CQ==,type:comment]
example_array:
    - ENC[AES256_GCM,data:vNoP+QGGjpF72vd0OK8=,iv:8mVoj1nC+tz/pOEda0Jjxzt+AaB48K3jCMUEhvAUaUU=,tag:aelMtoEh/u4DH78jipAxkA==,type:str]
    - ENC[AES256_GCM,data:wWsLqcGJt2FGY4boTwg=,iv:Uxjb/0fxvCFVo7OowpOFarfpjuQfXWWb5yp4a72W7e8=,tag:E68cWgaB0jbNldQy9o8gUg==,type:str]
example_number: ENC[AES256_GCM,data:oyTJPYR0fdJ4wg==,iv:hQgKG8xOzEsmqVoPMTsS481QBo1oKhXH2xfrgo4/Y1Q=,tag:RIVY7xY/n08HzErQKXuxrA==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:PcaChQ==,iv:73Q6KJfp/ByWXCpP3OCE1OydKPQPfGevGm0j3BktPBo=,tag:DoH1U3xDdRAXveLqBrGYZg==,type:bool]
    - ENC[AES256_GCM,data:6i27vT4=,iv:jnkzwrV7QIthA4sngR0K4EH4t9aIQ3/gBEsoUoP+cuA=,tag:Uv+1k8x+6Uid77KTkcqQfQ==,type:bool]
sops:
    age:
        - recipient: age1zlmedva0jsdys79d39qgy595clx5zemjzl2w0qpgewq2psj5yggswgltf2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUamwxL0ZIazhuYXdIVVQ0
            SFV6SG1QcnRuNFR0UEpkOVVBK3pqRnRUUlE4CkZ3T0RkL21sN2xqUVlvelNMQkdv
            V2hmUlNlOUVuTHAvYlFBdTZoZGNzR2sKLS0tIEdzaDRFZGxZN2dCNVRKZmNSakNk
            YUF4cEN3eGRyZWpPUU53dEYzSDI0TE0KmsMhlpw+eD97xzDugGLR5Jx+0ydOS8E9
            WzRRY4YDBq1YTrqAr00rO9icuGrNixttd6NiEQ4oTIN0oYq8dF3Shg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r9g435pu74yvnp8t44jj7z4qfj829v3w43ae7fgzxvusqu3y9cnq9pute3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNTFZMzR0UU13SnhNeG5M
            SVRwdEk2bDErQk9Ta3Z3eDVKS0NYRzhiUWlVCmVRTnBpZzZOU3ZmYWNzRi90Rk0y
            bjhKK3FiQWt1T09FZVhJb3hmaURmcVUKLS0tIGJWaGpZdTczMU1UbThEZFkzKzJs
            TmJBZkZyb0N6cFFWZW9YYlRiRlY2WHcKH+ewu0E0ORW6ydMtfzDBmvWKAMBlpixz
            FQ4EPgeEkhsX/As71m3Tq55/KBnetlRAlQN+FB7aOs1/JpWEWqSo9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10fg3nznhct8ke3h2yckdxp2vm3hhh5ej9s3w4adzm8p55twamsrqhnaq3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dC9HRmw5c3RtTVNhUktj
            cW9VY2tLWm9EVGZxZDE4RXU5TjhVQ0QxelNFCi85RW9rV28wdHNPYmpBNVlIZUsr
            V1Vjcy9TNUNCeXg3RDB6QWxnaW43VkEKLS0tIHlNb25BME03VFBuM0RZREFDMHhT
            MHk4ODRYY3hoRXFKaWt6MWVoQXBaWlEK7A1vwCHXCarmfaRjyUMDDyVk9STKLJxW
            PNmT+PcpaKN2eJC9+v3BRwojuEFn4/SnHpFah4LUcTLEAxUfOCIB9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T16:43:11Z"
    mac: ENC[AES256_GCM,data:mAQ/kMTRH3m4Kvc5sIru/EWcYk5JQ2CCtfRvL4SaSXCC834lnJVQEzjq7PHyKvwsgl8lNeDQVKiMqsL3TrnFAN+OlTgKYaA7KJzDDj+CNI5O0uJR5+gA1DdcZN5o17671p1e/DgT+2H+4/A3yA0we4WF8jJeb4cEi7nxlXE+juw=,iv:PSZJSdu8BiSwO5GZ6ZBKBzQfPw1f8KV4cjlY8WHA2oc=,tag:6I0wriXvGMPhiCRpxLLkZg==,type:str]
    pgp:
        - created_at: "2026-06-12T21:22:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4SYQepcDT7yARAAvY++pHp7+d7AZlSYHJwgqnT96hNH2vygDHYH4yxbZtbU
            SS55gDae8jo0CL1aFDZfX9xGtszxTc5e41p2I7eIHxuMnEnlWySmmKkk48JoDD3v
            SnJog3we/obxEqXQJSwB++aGf1jnCb+/+EcjZEcBwU06eF2Z7ENoPW7yqxZ9kc6v
            o/yJ23U9Ze1SBavKCd1AXYqhgo5W8P06ejdTRJPddE5eUithUG99c61mcnoi3Ymj
            DkjIJK0gcL05iQQiyxz0Q2uaWmFj7q/U2s9ysewJW0Km5mcJCEzyfIx4MybxUfzE
            P4Biv6xX/VliIk12RGb+wkhltV+/Kp7sONJm7xfmCJhavFW2gqLqaUayVn5ACRwb
            nAIgJaEOYHSAiPn2UQ2PXxHpAeUAZ/ab/VJqQj60JV4q8/WFOMDBrj1HkjKQpxVi
            Aqq/ajSJ3THRDlkE5FHSUmMpWjDv1OBgBdBEMX5VVG3G2FXFQE99eonyeN/UlpmX
            Z0C0mrUdqa/QqNVxr3U4vpIrOS6G0K2GrIlOXaTU/v1qnMxyJYP2j34HxNI3Jb6N
            ZLz7TCRZWg0ef5X24Inv6angK8b1NNsqTcgQBLSMF23ZIFHG9IG16n2S+tYZGDi/
            u0+R2gadcexuJSi3VnfmCjplHPKgN72G6ygObEhV7NM4RsOg7eaW8lUm1eEkQcDS
            WAEESlbVKSRCXKMAcVaPjALb9AI8ZHWQ6O+Jf+Ye6VA6iqyQAFuj6EFLYX0hyR/H
            H8ePXyHWx2kSESvn4OGZB4ficObt36H6cN81L/4KgWIXtUnLcOcOPFI=
            =ZK8l
            -----END PGP MESSAGE-----
          fp: B054287D42FC91AD36137D9F03ECA132FD38CD59
    unencrypted_suffix: _unencrypted
    version: 3.12.1
