hello: ENC[AES256_GCM,data:BgjWrX1OTEsopVx3Umibim+aCG2WxqBcS1hSOg==,iv:Vj4+RbsImNz9YWdLebnWzuKJRditHWvsrt1jk1mdDHM=,tag:hdpYOBO4eNUFYMzkJPQzsQ==,type:str]
example_key: ENC[AES256_GCM,data:SE8N6CvdwRdKEwQQYA==,iv:EbDrKoCVxj87ONO6r0P5ap3D30pXFJHikcHnS/7DbTw=,tag:7P8LUtsRjURF99p1iz6IEw==,type:str]
#ENC[AES256_GCM,data:tLJyi9zAX/Ij+IURNHED2g==,iv:GlQUzmajAe7p3YvCrieOKeukPvQ26YKQAH/rh/5Bq1c=,tag:r2ZAxS8kjYSrDm5iRsB2CQ==,type:comment]
example_array:
    - ENC[AES256_GCM,data:vNoP+QGGjpF72vd0OK8=,iv:8mVoj1nC+tz/pOEda0Jjxzt+AaB48K3jCMUEhvAUaUU=,tag:aelMtoEh/u4DH78jipAxkA==,type:str]
    - ENC[AES256_GCM,data:wWsLqcGJt2FGY4boTwg=,iv:Uxjb/0fxvCFVo7OowpOFarfpjuQfXWWb5yp4a72W7e8=,tag:E68cWgaB0jbNldQy9o8gUg==,type:str]
example_number: ENC[AES256_GCM,data:oyTJPYR0fdJ4wg==,iv:hQgKG8xOzEsmqVoPMTsS481QBo1oKhXH2xfrgo4/Y1Q=,tag:RIVY7xY/n08HzErQKXuxrA==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:PcaChQ==,iv:73Q6KJfp/ByWXCpP3OCE1OydKPQPfGevGm0j3BktPBo=,tag:DoH1U3xDdRAXveLqBrGYZg==,type:bool]
    - ENC[AES256_GCM,data:6i27vT4=,iv:jnkzwrV7QIthA4sngR0K4EH4t9aIQ3/gBEsoUoP+cuA=,tag:Uv+1k8x+6Uid77KTkcqQfQ==,type:bool]
sops:
    age:
        - recipient: age1zlmedva0jsdys79d39qgy595clx5zemjzl2w0qpgewq2psj5yggswgltf2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESlpvY0YvVHpPZmMwMDJv
            TVFvU05TYWlJNkZ5ZklOY0R6QzVnclROQm1BClQ4KzZsWkJBeHRYNGZybnE0UzNl
            dVBZalZPUTFsNVFFcW9yRkUrdi85K2sKLS0tIEk5UDZtQWZiYWxqTkxGU1BvM3dJ
            aVAvUkltTktUNGlBS083bEF4MXBYYnMKTQ+RbMvPPGSC2WFWFygsfmSF4TNnMPi8
            EpCIX2gdLL9kwMJMg3hjdSNFnyHFYpGt7FNYqBQVtSwVC2bI50DEAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r9g435pu74yvnp8t44jj7z4qfj829v3w43ae7fgzxvusqu3y9cnq9pute3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcjNwWExNTzlTa2VuVERM
            b0tWd3oxNnJkVGEvMFNpdnEyaitRSTZjZjA0ClhNMkxUTnhBbkJOcUFYaldzaTIv
            Uml2eGdIdHdBRGV0NnpsQzJJQXdLRzgKLS0tIDdoSDcwNjBnOXZZcE1IYUxXRVlp
            SVZFTmlmQVJ0SFhHVTJ1U1RrbVdLaDQK4ry3UcyoIdIcVU/NIO839RexKtQKEFcZ
            1sfv+BDNNBRBcuHCt0/0/ko1sN/1hEA42XHzundlcviiutzyFU7TOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T16:43:11Z"
    mac: ENC[AES256_GCM,data:mAQ/kMTRH3m4Kvc5sIru/EWcYk5JQ2CCtfRvL4SaSXCC834lnJVQEzjq7PHyKvwsgl8lNeDQVKiMqsL3TrnFAN+OlTgKYaA7KJzDDj+CNI5O0uJR5+gA1DdcZN5o17671p1e/DgT+2H+4/A3yA0we4WF8jJeb4cEi7nxlXE+juw=,iv:PSZJSdu8BiSwO5GZ6ZBKBzQfPw1f8KV4cjlY8WHA2oc=,tag:6I0wriXvGMPhiCRpxLLkZg==,type:str]
    pgp:
        - created_at: "2026-04-08T17:01:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4SYQepcDT7yARAAu0QjJVRTzumYidYKbqf68ctctTksWOFJ0MIKAVgKSuYm
            v3/0L3bjoDDp6FIS4qJ2OTVpwxToHAiW/qCn5UmlDLDz/rVUjappDxI948RT0W5o
            q3r7b76ecH7kd80Aef9upxn1zgeDBIMoltZYyES9U/CjoClz9HyeVAN+oq+ZFw4z
            kmpxoJ/1QsB8DfmXJOBowM5OpJke7p598d0tXbaflNrXM2Qs9Iiovx2t1+g6Rvmb
            DUqDhblQV5FuvwNJI7DuyQ7btVMeDlFqrrvfHQ94MfDh6vI7ovm7ZpOYHeDM+9oy
            CtUn35pC93nviMo7gJvWtzPyRjRfcLLP/YDRpxg3PSC7lyw+CDPVxFWit4NGZjYt
            1akAkKMV4vLW855ACnakx+Sd9J5LLwzA1Cogol7J4PcGtsW7aDqeLIJpxajK2yE8
            f0AyLSYKZ5Q2G5bt7+mIc5e8E1Fzb24J4iuXhZj7S3riTBXlOfyR9jXq4k6QcOdh
            J7MecrpZ+H8pwCOT+wRRuKIfcPrpM39Z/Aosi3trZtMC1zv9ygb1NtDStwVYq/ve
            8CdXzGg1gCbJJa3sOXc1xT5gdxHrMgoYEwKvn9xLqgjEbKYVZCGAD7W1dXDa3N7X
            zZBrJxWgJyJrZbxe06B1pA3WONo+6pKdtx2wK49/TDbDQ/TW1f/jpNeg+rLJVtjS
            WAEbFBcMydVhOuHKjgWKYzehdJ19t8nWoN6s+alKPsMs/z+aY9FWIJiMKhhLdjcl
            5G0POPmrJ5TjwuziiUGvYzcHCoeuEkwfh61XiafuTEpiz7qgHoHE55M=
            =Z+Xs
            -----END PGP MESSAGE-----
          fp: B054287D42FC91AD36137D9F03ECA132FD38CD59
    unencrypted_suffix: _unencrypted
    version: 3.12.1
