# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
let mbp-touchbar = config.boot.kernelPackages.callPackage ./touchbar.nix { };
in {
  imports =
    [
      (modulesPath + "/hardware/network/broadcom-43xx.nix")
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    kernelPackages = pkgs.linuxPackages_latest;
    initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
    initrd.kernelModules = [ "kvm-intel" "applesmc" "hid-apple" "hid-appletb-kbd" "hid-appletb-bl" "intel_lpss_pci" "spi_pxa2xx_platform" "applespi" ];
    kernelModules = [ "kvm-intel" "applesmc" "hid-apple" "hid-appletb-kbd" "hid-appletb-bl" "intel_lpss_pci" "spi_pxa2xx_platform" "applespi" ];
    extraModulePackages = [ mbp-touchbar ];
    loader.systemd-boot.enable = true;
    loader.efi.canTouchEfiVariables = true;
    kernelParams = [ "mem_sleep_default=s2idle" ];
  };

  # Lid switch configuration
  services.logind.settings.Login = {
    HandleLidSwitch = "suspend";
    HandleLidSwitchExternalPower = "suspend";
    HandleLidSwitchDocked = "ignore";
  };
  systemd.services.enable-macbook-wakeup = {
    description = "Enable wake sources for MacBook lid open";
    wantedBy = [ "multi-user.target" ];
    after = [ "multi-user.target" ];

    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };

    script = ''
      for device in LID0 XHC1 XHC2 RP01 RP05; do
        if grep -q "^$device.*disabled" /proc/acpi/wakeup; then
          echo "$device" > /proc/acpi/wakeup
        fi
      done
    '';
  };

  fileSystems."/" =
    {
      device = "/dev/mapper/luks-d8ee6f8b-f5f6-469f-9ada-83940c0f076d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-d8ee6f8b-f5f6-469f-9ada-83940c0f076d".device = "/dev/disk/by-uuid/d8ee6f8b-f5f6-469f-9ada-83940c0f076d";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/5F66-17ED";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
