# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
let mbp-touchbar = config.boot.kernelPackages.callPackage ./touchbar.nix { };
in {
  imports =
    [
      (modulesPath + "/hardware/network/broadcom-43xx.nix")
      (modulesPath + "/installer/scan/not-detected.nix")
      (modulesPath + "/hardware/apple-touchbar.nix")
    ];

  boot = {
    kernelPackages = pkgs.linuxPackages_latest;
    initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
    initrd.kernelModules = [ "kvm-intel" "applesmc" "hid-apple" "hid-appletb-kbd" "hid-appletb-bl" "appletbdrm"  "intel_lpss_pci" "spi_pxa2xx_platform" "applespi" ];
    kernelModules = [ "kvm-intel" "applesmc" "hid-apple" "hid-appletb-kbd" "hid-appletb-bl" "appletbdrm" "intel_lpss_pci" "spi_pxa2xx_platform" "applespi" ];
    extraModulePackages = [ mbp-touchbar ];
    loader.systemd-boot.enable = true;
    loader.efi.canTouchEfiVariables = true;
    kernelParams = [ "i915.enable_psr=0" "intel_iommu=on" ];
  };

  hardware.apple.touchBar = {
    enable = true; 
    settings = {
      DoublePressSwitchLayers = 200;
    };
  };
  
#  services.tiny-dfr.enable = true;

  services.libinput.enable = true;
  environment.etc."libinput/local-overrides.quirks".text = ''
    [MacBook(Pro) SPI Touchpads]
    MatchName=*Apple SPI Touchpad*
    ModelAppleTouchpad=1
    AttrTouchSizeRange=200:150
    AttrPalmSizeThreshold=1100

    [MacBook(Pro) SPI Keyboards]
    MatchName=*Apple SPI Keyboard*
    AttrKeyboardIntegration=internal

    [MacBookPro Touchbar]
    MatchBus=usb
    MatchVendor=0x05AC
    MatchProduct=0x8600
    AttrKeyboardIntegration=internal
  '';

  # Lid switch configuration
  services.logind.settings.Login = {
    HandleLidSwitch = "suspend";
    HandleLidSwitchExternalPower = "suspend";
    HandleLidSwitchDocked = "suspend";
  };
  systemd.services.enable-macbook-wakeup = {
    description = "Enable wake sources for MacBook lid open";
    wantedBy = [ "multi-user.target" ];
    after = [ "multi-user.target" ];

    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };

    script = ''
      if grep -q '^LID0[[:space:]].*disabled' /proc/acpi/wakeup; then
        echo LID0 > /proc/acpi/wakeup
      fi
    '';
  };
  systemd.services.fix-applespi-resume = {
    description = "Re-initialize Apple SPI input devices after resume";
    wantedBy = [ "post-resume.target" ];
    after = [ "post-resume.target" ];
    serviceConfig = {
      Type = "oneshot";
    };
    script = ''
      ${pkgs.kmod}/bin/modprobe -r applespi || true
      ${pkgs.kmod}/bin/modprobe applespi || true
    '';
  };

  fileSystems."/" =
    {
      device = "/dev/mapper/luks-d8ee6f8b-f5f6-469f-9ada-83940c0f076d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-d8ee6f8b-f5f6-469f-9ada-83940c0f076d".device = "/dev/disk/by-uuid/d8ee6f8b-f5f6-469f-9ada-83940c0f076d";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/5F66-17ED";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  networking.enableB43Firmware = lib.mkDefault true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableRedistributableFirmware = lib.mkDefault true;
}
